name: Merge upstream branches
on:
  schedule:
    - cron:  '0 0 * * 0'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Vedza'
          git config --global user.email 'Vedza@users.noreply.github.com'
          git pull --unshallow
          git remote add upstream https://github.com/andersfylling/disgord.git
          git fetch upstream
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
